from voltage_to_hex import voltage_to_hex;

test_voltages = [0.2, 0.5, 0.8, 1.1, 1.4]
expected_outputs = ['0x147', '0x333', '0x51e', '0x50a', '0x8f5']
outputs = list(map(voltage_to_hex, test_voltages));

print("OUTPUTS AS SPECIFIED BY INTEL: ", outputs);
print("OUTPUTS GENERATED BY THE SCRIPT:", expected_outputs)
